### ISSUE TITLE
Errors deploying

### ISSUE THREAD

**Issue by CloudCaesar** [afawcett/buildtogether#1]
=== Deploy Errors
PROJECT PATH                                                                ERRORS                                                                     
──────────────────────────────────────────────────────────────────────────  ───────────────────────────────────────────────────────────────────────────
force-app/main/default/permissionsets/BuildTogether.permissionset-meta.xml  In field: field - no CustomField named Account.OperatingHoursId found      
force-app/main/default/flexipages/Account_Record_Page1.flexipage-meta.xml   Your org doesn't have access to component runtime_sales_social:socialPanel.

**Comment by afawcett** [comment]
I used the scrartch org config in this repo and did not reproduce this issue. However I removed the above references just in case this helps. Thanks!
